%Demonstrates handling some events generated by the LabChart document.
%First an existing document is opened, event handlers are hooked up and
%a 5 seconds sampling session is started. While sampling, the latest data
%from channels 1 and 2 are plotted in MatLab.
%Once sampling has finished, the last 1 seconds of data in the first block
%is selected, causing the OnSelectionChange() event handler to plot the selection.
global gLCApp;
global gChans; %Array of channel numbers specifying channels to retrieve sampling data from
GetLCApp;  %defines global gLCApp
GSFolder = gLCApp.GettingStartedFolder;
%doc1 = gLCApp.Open(strcat(GSFolder,'\LabChart\Visual Evoked Potentials.adicht'));
%doc1 = gLCApp.Open(strcat(GSFolder,'\LabChart\Muscle Summation.adicht'));
doc1 = gLCApp.Open(strcat(GSFolder,'\LabChart\Reflex Reactions.adicht'));
%doc1 = gLCApp.Open(strcat(GSFolder,'\LabChart\Rabbit Respiration.adicht'));
%doc1 = gLCApp.Open(strcat(GSFolder,'\LabChart\Hoffman Reflex.adicht'));

gChans = [1 2] % collect sampling data from channels 1 and 2.

RegisterLCEvents(doc1); % hook up the OnSelectionChange event and the sampling events such as OnNewSamples and OnBlockStart.

doc1.StartSampling(5); %sample for 5 seconds
pause(8)               %wait for sampling to stop plus some
% now set a selection to demonstrate the OnSelectionChange event
blockIndex = 0;
blockLen = doc1.GetRecordLength(blockIndex);
secsPerTick = doc1.GetRecordSecsPerTick(blockIndex);
doc1.SelectChannel(1,1); %Turn on selection in Channel 2
%Select last 5 seconds in first block
doc1.SetSelectionRange(blockIndex,blockLen-5.0/secsPerTick,blockIndex,blockLen);

%ReleaseLCDoc(doc1); %uncomment this if finished with doc1.
%ReleaseLC();  %uncomment this if finished with gLCApp.
